language: csharp
sudo: required
solution: DevExpress.Xpo.ConsoleCoreDemo.sln
mono: none
dotnet: 2.1
dist: bionic
script:
 - cd Tutorials/Console/CS
 - dotnet restore
 - dotnet build -c Debug
 - cd ../../ASP.NET/MVC.RazorPages/CS
 - dotnet restore
 - dotnet build -c Debug
 - cd ../../ASP.NET/MVC.Core/CS
 - dotnet restore
 - dotnet build -c Debug 